[package]
name = "sqlm-postgres"
version = "0.1.0"
edition = "2021"

[features]
default = ["comptime", "json", "time", "uuid"]
comptime = ["sqlm-postgres-macros/comptime"]
json = ["sqlm-postgres-macros/json", "tokio-postgres/with-serde_json-1", "dep:serde_json"]
time = ["sqlm-postgres-macros/time", "tokio-postgres/with-time-0_3"]
uuid = ["sqlm-postgres-macros/uuid", "tokio-postgres/with-uuid-1"]

[dependencies]
deadpool-postgres = "0.10"
dotenvy = "0.15"
http-error = { git = "https://github.com/rkusa/http-error.git", rev = "7453f21" } # path = "../../http-error" }
once_cell = "1.17"
rustls = "0.21"
serde_json = { version = "1.0", optional = true }
sqlm-postgres-macros = { path = "../postgres-macros", default-features = false }
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.10"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }
postgres-types = { version = "0.2", features = ["derive"] }

[build-dependencies]
rustversion = "1.0"
