[package]
name = "sqlm-postgres"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio-postgres-rustls = "0.10"
tokio-postgres = "0.7"
deadpool-postgres = "0.10"
once_cell = "1.17"
rustls = "0.21"
dotenvy = "0.15"

[dev-dependencies]
sqlm-postgres-macros = { path = "../postgres-macros", default-features = false, features = ["comptime"] }
tokio = { version = "1.0", features = ["macros"] }

[build-dependencies]
rustversion = "1.0"
