[package]
name = "sqlm-postgres"
version = "0.1.0"
edition = "2021"

[features]
default = ["comptime"]
comptime = ["sqlm-postgres-macros/comptime"]

[dependencies]
deadpool-postgres = "0.10"
dotenvy = "0.15"
once_cell = "1.17"
rustls = "0.21"
sqlm-postgres-macros = { path = "../postgres-macros", default-features = false }
tokio-postgres = "0.7"
tokio-postgres-rustls = "0.10"

[dev-dependencies]
tokio = { version = "1.0", features = ["macros"] }

[build-dependencies]
rustversion = "1.0"
